### velocity\u914D\u7F6E
spring:
  velocity:
    suffix: .html
    toolbox-config-location: toolbox.xml
    enabled: true
    resource-loader-path: classpath:/templates/

### \u6570\u636E\u6E90
  datasource:
    ### \u4E3B\u5E93
    master:
      url: jdbc:mysql://localhost:3306/wenda?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
    ### \u4ECE\u5E93
    slave:
      url: jdbc:mysql://localhost:3306/wenda?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
mysql:
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource

### mybatis\u914D\u7F6E
mybatis:
  config-location: classpath:mybatis-config.xml


### \u670D\u52A1\u5668\u542F\u52A8\u7AEF\u53E3\u914D\u7F6E
server:
  port: 8000


